# FlatOut UC Time Trial Ghosts by Chloe @gaycoderprincess
# enjoy, nya~ :3

[main]
enabled = true						# Set this to false to disable the time trial mode & ghosts, useful if you only want the input display
ghost_visuals = 2					# 0 - Always show the entire car, 1 - always show the car as a ghost, 2 - only make the car a ghost when near it
disable_props = false					# Removes all dynamic objects from the map
nitro_option = 1					# 0 - none, 1 - normal, 2 - double, 3 - infinite
show_best_times = true					# Displays the best lap times you've ever achieved for a track on the top right in-game
show_best_times_in_session = true			# Displays the best lap times you've achieved in the current session on the top right in-game

[extras]
view_replays = false					# View & spectate replays for a track